"""Generate display-width ranges from Python's bundled Unicode database."""
from pathlib import Path
import unicodedata as u


def ranges(predicate):
    result = []
    start = last = None
    for code in range(0x110000):
        if predicate(chr(code)):
            if start is None:
                start = code
            last = code
        elif start is not None:
            result.append((start, last))
            start = None
    if start is not None:
        result.append((start, last))
    return result


tables = {
    'ZERO': ranges(lambda c: u.category(c) in ('Mn', 'Me')),
    'WIDE': ranges(lambda c: u.category(c) != 'Cn' and u.east_asian_width(c) in ('W', 'F')),
    'FORMAT': ranges(lambda c: u.category(c) == 'Cf'),
}
output = [f'// Generated by tools/generate_widths.py using Unicode {u.unidata_version}.\n']
for name, entries in tables.items():
    output.append(f'pub const {name}: &[(u32, u32)] = &[\n')
    output.extend(f'    (0x{start:x}, 0x{end:x}),\n' for start, end in entries)
    output.append('];\n')
Path('src/unicode_widths.rs').write_text(''.join(output))
